printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
trailingComma: es5
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
plugins:
  - "prettier-plugin-svelte"
  - "prettier-plugin-organize-imports"
  - "prettier-plugin-tailwindcss"
pluginSearchDirs:
  - "./src/"
overrides:
  - files: "*.svelte"
    options:
      parser: "svelte"
tailwindConfig: "./tailwind.config.cjs"
